### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2264'

### ISSUE THREAD

**Issue by uralskayamariya** [nerevar/stock_prices#1]
Hello!
Then I try: 
make cron DAY=2019-05-10
get this error:
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    args.fn(args)
  File "C:\DS\stock_prices\lib\downloader.py", line 27, in downloader
    get_moex_data(args.engine, args.market, day_str, save_raw_xml=args.save_raw_xml)
  File "C:\DS\stock_prices\lib\moex_downloader.py", line 152, in get_moex_data
    get_moex_data(engine, market, date_str, start + pagination['page_size'], save_raw_xml)
  File "C:\DS\stock_prices\lib\moex_downloader.py", line 140, in get_moex_data
    save_to_csv(valid_quotes, engine, market, date_str, quote_attrs if start == 0 else None)
  File "C:\DS\stock_prices\lib\moex_downloader.py", line 60, in save_to_csv
    writer.writerow(row.values())
  File "C:\Program Files\Python38\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2264' in position 69: character maps to <undefined>
make: *** [Makefile:35: download_moex] Error 1

How it to fix?

**Comment by nerevar** [comment]
Probably, you can try to change this line https://github.com/nerevar/stock_prices/blob/master/lib/moex_downloader.py#L52
to
`outfile = open(filepath, 'a' if os.path.exists(filepath) and header_attrs is None else 'w', encoding='utf-8')`

**Comment by uralskayamariya** [comment]
Thank you, it's working!
